### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by LYQ1107** [RainBowLuoCS/DiffusionTrack#1]
Dear author thank you very much for your excellent work! Are files such as  /datasets  missing in  yolox/data/ ? I encountered missing 'DiffusionMosaicDetection' from 'yolox.data' and 'MosaicDetection' from 'yolox.data' while training

**Comment by RainBowLuoCS** [comment]
Thanks for your reminder, now the missing files are added and work fine, good luck!

**Comment by LYQ1107** [comment]
Thank you for your amazing work!
