### ISSUE TITLE
Not find "diffusiontrack_ablation_det.pth.tar"

### ISSUE THREAD

**Issue by wjy327** [RainBowLuoCS/DiffusionTrack#10]
Dear author thank you very much for your excellent work! I can not find "diffusiontrack_ablation_det.pth.tar".Can you help me?Thank you!

**Comment by wjy327** [comment]
还有diffusiontrack_mot17_det.pth.tar、diffusiontrack_mot17_det.pth.tar、diffusiontrack_mot20_det.pth.tar、diffusiontrack_dancetrack_det.pth.tar也找不到，希望您可以帮助我一下，真心地感谢您

**Comment by RainBowLuoCS** [comment]
you can refer to ByteTrack to download these weight files and then rename for safe loading.

**Comment by wjy327** [comment]
Thank you for your help, I understand now.
