### ISSUE TITLE
精度问题

### ISSUE THREAD

**Issue by hanzifan** [RainBowLuoCS/DiffusionTrack#11]
您好，我在Dancetrack上进行训练测试，精度奇低无比，HOTA只有23.7，同时我利用您提供的checkpoint进行inference精度也只有46.3

**Comment by RainBowLuoCS** [comment]
是加载了 bytetrack 检测权重后训练的结果嘛，可以检查看看是不是哪里出错了

**Comment by Long00River** [comment]
请问解决了么，我也遇到了类似问题，复现diffusion Track提交到mot challenge MOT17的结果为56.1，是中间步骤有问题么？我修改了yolox_xdiffusion_track_mot17.py中train改为test得到
![Uploading 1729562095236.png…]()

`class Exp(MyExp):
    def __init__(self):
        super(Exp, self).__init__()
        self.num_classes = 1
        self.depth = 1.33
        self.width = 1.25
        self.exp_name = os.path.split(os.path.realpath(__file__))[1].split(".")[0]
        self.train_ann = "train.json"
        self.val_ann = "val_half.json"
        self.test = "test.json" #添加test.json `
`        #注释上面train,改为test数据，测试论文结果
        valdataset = MOTDataset(
            data_dir=os.path.join(get_yolox_datadir(), "mot"),
            json_file=self.test,
            img_size=self.test_size,
            name='test',
            preproc=DiffusionValTransform(
                rgb_means=(0.485, 0.456, 0.406),
                std=(0.229, 0.224, 0.225),
                max_labels=1000, 
            )
        )
`

**Comment by Long00River** [comment]
![baidu](http://www.baidu.com/img/bdlogo.gif"百度logo")

**Comment by Long00River** [comment]
class Exp(MyExp):
    def __init__(self):
...
        self.test = "test.json"  # 添加
...

    def get_eval_loader(self, batch_size, is_distributed, testdev=False):
        valdataset = MOTDataset(
            ...
            #name='train', #将train,改为test数据，测试论文结果
            name='test',
            ...
            )
        )

**Comment by Long00River** [comment]
请问解决了么，我也遇到了类似问题，复现diffusion Track提交到mot challenge MOT17的结果为56.1，是中间步骤有问题么？我修改了yolox_xdiffusion_track_mot17.py中train改为test得到
![tmp](https://gist.github.com/user-attachments/assets/40eb7c67-0bd9-4393-bef4-ac2f6d2c8d33)
修改代码yolox_xdiffusion_track_mot17.py

    def __init__(self):
        self.test = "test.json"  # 添加


    def get_eval_loader(self, batch_size, is_distributed, testdev=False):
        valdataset = MOTDataset(
            ...
            #name='train', #将train,改为test数据，测试论文结果
            name='test',
            ...
            )
        )
