### ISSUE TITLE
关于提交MOTChallenge的疑问

### ISSUE THREAD

**Issue by Long00River** [RainBowLuoCS/DiffusionTrack#12]
你好，对您的工作非常感兴趣，我复现了您的部分工作内容，将mot17 test结果和train结果一起提交到mot challenge MOT17，可是结果仅为56.1，是中间步骤有问题么？

关于如何正确提交MOTChallenge困扰了很久，方便的话请解个惑，非常感谢~以下是我的提交内容：

首先使用命令：
python3 tools/track.py -f exps/example/mot/yolox_x_diffusion_track_mot17_ablation.py -c pretrained/diffusiontrack_ablation_track.pth.tar -b 1 -d 1 --fuse；得到了7个文件，手工复制成21个，分别重命名为-DPM/-FRCNN/-SDP；
其次修改yolox_xdiffusion_track_mot17.py中的内容，将train改为test，得到另21个文件。
![tmp](https://github.com/user-attachments/assets/b3712d27-0d36-41c4-937f-bdba77036a43)

修改yolox_xdiffusion_track_mot17.py代码部分：

    def __init__(self):
        self.test = "test.json"  # 添加

    def get_eval_loader(self, batch_size, is_distributed, testdev=False):
        valdataset = MOTDataset(
            ...
            #name='train', #将train,改为test数据，测试论文结果
            name='test',
            ...
            )
        )
最后打包21+21共42个文件上传得到评估结果；

**Comment by RainBowLuoCS** [comment]
是不是实验配置问题呢，你的测试参数是什么呀，是否使用了我提供的脚本
以下是我的测试结果
![image](https://github.com/user-attachments/assets/06c571e7-6da1-4813-83fd-23c12ea84d73)

**Comment by Long00River** [comment]
看来是我配置有问题，请问测试参数是说哪里的？需要怎么配置呀？我是按照README提示跑的代码，
![1729773258185](https://github.com/user-attachments/assets/a6306121-44e9-409d-be84-37a1ba386efa)
运行结果生成了7个文件：
![image](https://github.com/user-attachments/assets/d97c12a8-5d2b-4ece-8cee-ce232bba046c)

**Comment by gffgghvbj** [comment]
作者你好，我也遇到了这个问题，根据你README中的测试方法，得到的结果不尽人意。
请问你是如何配置测试脚本的，能否提供测试时所使用的全部参数
