### ISSUE TITLE
pretrained/diffusiontrack_ablation_track.pth.tar

### ISSUE THREAD

**Issue by haust-ty** [RainBowLuoCS/DiffusionTrack#14]
您好，我想请问一下当我想 Evaluation on MOT17 half val的时候，这个pretrained/diffusiontrack_ablation_track.pth.tar模型参数我该如何获得，又或者这是哪一个模型的重命名？

**Comment by RainBowLuoCS** [comment]
抱歉，如果我没有提供的话那就需要自己从头训练了，三个测试集上的 full train 版本应该都有提供
