### ISSUE TITLE
# 3sigma = 1/2 --> sigma: 1/6

### ISSUE THREAD

**Issue by zengxiansen-V** [RainBowLuoCS/DiffusionTrack#16]
if num_gt < self.num_proposals:
    # 补充随机生成的box到num_proposals,方便后续产生固定数量的diffusion的box
    box_placeholder = torch.randn(self.num_proposals - num_gt, 4,
                                  device=self.device,dtype=self.dtype) / 6. + 0.5  # 3sigma = 1/2 --> sigma: 1/6 ???

您好，请问训练代码中，用于生成固定数量的噪声框中提到 # 3sigma = 1/2 --> sigma: 1/6 ，这里应该怎么理解呢？

**Comment by RainBowLuoCS** [comment]
我现在比较忙，我记得是控制方差，加速收敛

**Comment by zengxiansen-V** [comment]
我好像突然理解了，是不是按照68-95-99.7规则，将99.7%落在[-3, 3]范围的值控制落到[0, 1]

**Comment by RainBowLuoCS** [comment]
Right!
