### ISSUE TITLE
Question about HungarianMatcherDynamicK

### ISSUE THREAD

**Issue by yulin010101** [RainBowLuoCS/DiffusionTrack#2]
Hello author, I am confused about the following code. Can you please explain the meaning of this?

https://github.com/RainBowLuoCS/DiffusionTrack/blame/cd1b1d4cc004a97921d8cad3337ecd97d6902206/diffusion/models/diffusion_losses.py#L344

**Comment by RainBowLuoCS** [comment]
It is a part of 3D GIOU loss calculation process. We will soon release our model weight and extra appendix with the kinds of details.

**Comment by yulin010101** [comment]
I see. Thank you for your explanation.

**Comment by hmg2023** [comment]
Hello author, How long can the model weight be released?

**Comment by RainBowLuoCS** [comment]
the paper is under review (model weight coming soon, please stay tuned)
